### ISSUE TITLE
Submit buttom doesn't work

### ISSUE THREAD

**Issue by pmros** [afader/thompson-regex-js#1]
First of all, thank you for your project!
I've noted that submit buttom doesn't work at [demo site](http://afader.github.io/thompson-regex-js/), however enter key does.
By the way, I created a project called [pamatcher](https://github.com/pmros/pamatcher) that use Thompson's NFA construction algorithm too, but in order to create a more general pattern matcher than regular expressions. Maybe you like it.

**Comment by afader** [comment]
Thanks for the feedback! Your project looks interesting, and is also
exactly the goal of what I'm doing here: general pattern matching over
sequences. I'd say we should combine forces, but another personal goal here
is to learn about javascript. :)

**Comment by afader** [comment]
Should be fixed now. I managed to do it in less than five years.
